<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<NoWarn>$(NoWarn);SKEXP0110</NoWarn>
	<UserSecretsId>dd0ae43f-ef85-42b9-8fd2-07312cdf759d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.AI.Inference" Version="13.4.2-preview.1.26303.6" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.2" />
    <PackageReference Include="Aspire.OpenAI" Version="13.4.3-preview.1.26305.13" />
    <PackageReference Include="CommunityToolkit.Aspire.OllamaSharp" Version="13.4.0" />
	<PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.Extensions.AI" Version="10.7.0" />
    <PackageReference Include="Microsoft.Extensions.AI.AzureAIInference" Version="10.0.0-preview.1.25559.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.77.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" Version="1.77.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureAIInference" Version="1.77.0-beta" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.InMemory" Version="1.74.0-preview" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Ollama" Version="1.77.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.77.0" />
	<PackageReference Include="Microsoft.Agents.AI" Version="1.6.2" />
	<PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.6.2" />
	<PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HRAssistant.ServiceDefaults\HRAssistant.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
